version: '3.1'

services:
  mongo:
    image: mongo:latest
    hostname: test_mongodb
    container_name: mongo
    environment:
      - MONGO_INITDB_DATABASE=animal_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./backend/init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
      - mongodbdata:/data/db
    networks:
      - app-network
  
  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://root:pass@mongo:27017/
    networks:
      - app-network
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - backend
    networks:
      - app-network
    ports:
      - "80:80"

networks:
  app-network:
    driver: bridge

volumes:
    mongodbdata: