version: '3.8'

services:
  mongo:
    image: mongo:latest
    hostname: test_mongodb
    container_name: mongo
    environment:
      - MONGO_INITDB_DATABASE=animal_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGODB_DATA_DIR: /data/db
    volumes:
      - ./backend/init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
      - mongodbdata:/data/db
    networks:
      - app-network
        
  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://admin:admin@mongo:27017/
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - backend
    networks:
      - app-network
    ports:
      - "80:80"

  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - frontend
  #   networks:
  #     - app-network
  #   volumes:
  #     - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - /app/build:/usr/share/nginx/html

networks:
  app-network:
    driver: bridge

volumes:
    mongodbdata:
        driver: local